---
name: '☑️ Checks Pipeline'
description: 'Checks the codebase health'

inputs:
    run-tests-command:
        description: 'Run tests command, default is `npm test`'
        default: 'npx nx affected --target test'
        required: false

    run-tests:
        description: 'Run tests'
        default: 'true'
        required: false

    run-lint-command:
        description: 'Run linter command, default is `npm run lint`'
        default: 'npx nx affected --target lint'
        required: false

    run-lint:
        description: 'Run lint'
        default: 'true'
        required: false

    run-build-command:
        description: 'Run build command, default is `npm run build`'
        default: 'npx nx affected --target build'
        required: false

    run-build:
        description: 'Run build'
        default: 'true'
        required: false

runs:
    using: composite
    steps:
        - name: 🖥️ Setup Env
          uses: ./.github/workflows/install

        - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
          uses: nrwl/nx-set-shas@v4
          with: { main-branch-name: 'master' }

        - name: 🧪 Test
          if: ${{ inputs.run-tests == 'true' }}
          shell: bash
          run: |
              ${{ inputs.run-tests-command }}

        - name: 🔨 Build
          if: ${{ inputs.run-build == 'true' }}
          shell: bash
          run: |
              ${{ inputs.run-build-command }}

        - name: ✅ Lint
          if: ${{ inputs.run-lint == 'true' }}
          shell: bash
          run: |
              ${{ inputs.run-lint-command }}
